domain: beenz.co
url: https://beenz.co
baseurl: "/beenz"

title: Love, Sheena
email: hc3550@nyu.edu
author: Sheena Chiang

lang: en

plugins:
  - jekyll-seo-tag

theme: wind-theme

color: "#B85042"
# disqus:
#   shortname: example-com
#
rrss:
  email: "hc3550@nyu.edu"
  telegram: "https://t.me/"
  discord: "https://discord.com/"
  linkedin: "www.linkedin.com/in/hsin-chiang"

